// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend_challenge.Data;

namespace backend_challenge.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210930214632_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("backend_challenge.Data.Empregado", b =>
                {
                    b.Property<int>("id_empregado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("endereco")
                        .HasColumnType("longtext");

                    b.Property<string>("primeiro_nome")
                        .HasColumnType("longtext");

                    b.Property<int>("telefone")
                        .HasColumnType("int");

                    b.Property<string>("ultimo_nome")
                        .HasColumnType("longtext");

                    b.HasKey("id_empregado");

                    b.ToTable("Empregados");

                    b.HasData(
                        new
                        {
                            id_empregado = 1,
                            endereco = "big.boss@company.com",
                            primeiro_nome = "Big",
                            telefone = 936854270,
                            ultimo_nome = "BOSS"
                        },
                        new
                        {
                            id_empregado = 2,
                            endereco = "jonas.xavier@company.com",
                            primeiro_nome = "Jonas",
                            telefone = 936854271,
                            ultimo_nome = "Xavier"
                        },
                        new
                        {
                            id_empregado = 3,
                            endereco = "linus.torvalds@company.com",
                            primeiro_nome = "Linus",
                            telefone = 936854272,
                            ultimo_nome = "TORVALDS"
                        },
                        new
                        {
                            id_empregado = 4,
                            endereco = "jimmy.wales@company.com",
                            primeiro_nome = "Jimmy",
                            telefone = 936854273,
                            ultimo_nome = "WALES"
                        },
                        new
                        {
                            id_empregado = 5,
                            endereco = "larry.page@company.com",
                            primeiro_nome = "Larry",
                            telefone = 936854274,
                            ultimo_nome = "PAGE"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
